# Generated by Django 3.1.4 on 2021-02-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=7)),
                ('mobile', models.BigIntegerField()),
                ('registration_no', models.IntegerField()),
                ('year', models.DateField()),
                ('receipt_no', models.IntegerField(max_length=10)),
                ('area', models.CharField(max_length=255)),
                ('survey_no', models.IntegerField(max_length=255)),
                ('plant_caste', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('कोष_बाजारपेठ_नाव', models.CharField(max_length=255)),
                ('पावती_क्रमांक', models.IntegerField()),
                ('दिनांक', models.DateField()),
                ('चांगल्या_कोषांचे_वजन_कि_ग्रॅ', models.BigIntegerField()),
                ('इतर_कोष_कि_ग्रॅ', models.FloatField()),
                ('चांगल्या_कोषांना_मिळालेला_दर_प्रति_कि_ग्रॅ', models.FloatField()),
                ('एकुण_कोष_कि_ग्रॅ', models.FloatField()),
                ('एकुण_रक्कम', models.FloatField()),
            ],
            options={
                'verbose_name': 'form3',
                'verbose_name_plural': 'form3s',
            },
        ),
        migrations.CreateModel(
            name='form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grenege_name', models.CharField(max_length=255)),
                ('Andipunjpavati_no', models.IntegerField()),
                ('date', models.DateField()),
                ('Andipunj_jaat', models.CharField(max_length=255)),
                ('Andipunj_count', models.IntegerField()),
                ('center_name', models.CharField(max_length=255)),
                ('hatching_date', models.DateField()),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmer_registration')),
            ],
        ),
    ]
