# Generated by Django 3.1.4 on 2021-02-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form3',
            options={},
        ),
        migrations.AddField(
            model_name='form3',
            name='farmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smis.farmer_registration'),
        ),
        migrations.AlterField(
            model_name='form2',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smis.farmer_registration'),
        ),
        migrations.CreateModel(
            name='form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('चांगल्या_कोषांना_मिळालेला_दर_प्रति_कि_ग्रॅ', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Andipunj_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smis.form2')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smis.farmer_registration')),
                ('चांगल्या_कोषांचे_वजन_कि_ग्रॅ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smis.form3')),
            ],
        ),
    ]
