# Generated by Django 3.1.5 on 2021-03-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smis', '0002_auto_20210224_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form4',
            old_name='चांगल्या_कोषांचे_वजन_कि_ग्रॅ',
            new_name='good_kosh_count',
        ),
        migrations.RemoveField(
            model_name='form4',
            name='चांगल्या_कोषांना_मिळालेला_दर_प्रति_कि_ग्रॅ',
        ),
    ]
