# Generated by Django 3.1.5 on 2021-03-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smis', '0004_auto_20210304_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form4',
            old_name='Andipunj_count',
            new_name='sarasari_kosh_kg',
        ),
    ]
