# Generated by Django 3.1.7 on 2021-03-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smis', '0005_auto_20210304_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form3',
            old_name='दिनांक',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='चांगल्या_कोषांचे_वजन_कि_ग्रॅ',
            new_name='good_kosh_kg',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='इतर_कोष_कि_ग्रॅ',
            new_name='good_kosh_rate_kg',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='कोष_बाजारपेठ_नाव',
            new_name='kosh_bajarpeth_name',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='एकुण_कोष_कि_ग्रॅ',
            new_name='other_kosh_kg',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='पावती_क्रमांक',
            new_name='pavti_no',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='एकुण_रक्कम',
            new_name='total_kosh_amount',
        ),
        migrations.RenameField(
            model_name='form3',
            old_name='चांगल्या_कोषांना_मिळालेला_दर_प्रति_कि_ग्रॅ',
            new_name='total_kosh_kg',
        ),
    ]
